---
# BEGIN
spring:
  datasource:
    password: ycNwzWDRxaCUogU6pFpRaNIEGg7m9CW6
    url: postgresql://web:ycNwzWDRxaCUogU6pFpRaNIEGg7m9CW6@dpg-ctdefupopnds73akha00-a/web_9g4d
    username: web
# END
